required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

 [[constraint]]
   branch = "master"
   name = "k8s.io/client-go"

 [[constraint]]
   branch = "master"
   name = "k8s.io/code-generator"
